# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CC Rights Back Resource
author: Creative Commons
email: info@creativecommons.org
description: >- # this means to ignore newlines until "baseurl:"
 <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">CC Rights Back Resource</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/creativecommons.org/tot-international" property="cc:attributionName" rel="cc:attributionURL">Creative Commons</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: creativecommons
github_username:  creativecommons

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'countries'
    template: 'country'
    name: 'country'
    dir: 'country'
  - data: 'legislation'
    template: 'legislation'
    name: 'title'
    dir: 'country/#{sanitize_filename(data["country"])}/legislation'
  - data: 'bills'
    template: 'bill'
    name: 'title'
    dir: 'country/#{sanitize_filename(data["country"])}/bill'
  - data: 'decisions'
    template: 'decision'
    name: 'case'
    dir: 'country/#{sanitize_filename(data["country"])}/decision'
  - data: 'resources'
    template: 'resource'
    name: 'title'
    dir: 'country/#{sanitize_filename(data["country"])}/resource'
